server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway #服务名字
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 #nacos地址
    gateway:
      routes: #网关路由配置
        - id: user-service #路由id，自定义，唯一
          uri: lb://userService  #路由目标地址，userService为服务名称
          predicates:  #断言，判断是否路径匹配
            - Path=/user/**   #只要由/user开头就符合要求
        - id: order-service
          uri: lb://orderService
          predicates:
            - Path=/order/**
